### PR TITLE
Fix utf-8 encoding bug for bookmark title 

### LINKED ISSUE #1: Problem with encoding in ~/.config/google-chrome/Default/Bookmarks
The problem is located in chrome.py file. It happens when a website has an accent in its title or description. 

Regards,

Antoine VASTEL

### PR DESCRIPTION
**Pull request by antoinevastel**
This commit correctly reads bookmark files with non ascii characters.

Also added a missing dependancy in docker/os/run/ubuntu/dockerfile  (libgconf-2-4) necessary to start some versions of chrome.

Also reduced the sleep time to 1sec.

fixes #1 
fixes #2

### CODE REVIEW

**Comment by plaperdr** [comment]
Waoh! Thanks a lot for looking into the source code and test Blink!
I have two small questions regarding your pull request:
- Is libgconf-2-4 also necessary for the Fedora Docker image or is it just for Ubuntu?
- I have seen that you have removed the "--no-sandbox" argument from the Chrome launch script. Do the OS containers (Ubuntu and Fedora) have all the necessary files to launch a complete sandbox?
  Thanks a lot!

**Comment by antoinevastel** [comment]
I forgot to introduce myself. I am Antoine Vastel and I am currently doing an internship in INRIA Lille in the team of Mr Rudametkin.

Concerning libgconf-2-4 I think it is only necessary for Ubuntu. I have ran many test before an after and that is what i concluded.

About the --no-sandbox I think the containers do not have enough files to launch a complete sandbox. However, if I let the option --no-sandbox Google Chrome warns me that this flag is depreciated. Without it there is no more problem.

Regards,

Antoine VASTEL

**Comment by plaperdr** [comment]
Ah, you're with Walter! :) Great to have you on board! If you have any questions regarding the project, don't hesitate to contact me by mail!
To optimize containers, could you add "&& apt-get clean" after "RUN apt-get install -y libgconf-2-4" in the Ubuntu Dockerfile? I'll accept your pull request after that.

**Comment by antoinevastel** [comment]
I've done the modification. It should be ok now :)

**Pull request merged**
